#!/bin/sh
set -e

echo "Making .deb"
PYTHONPATH=. debian/changelog.py
fakeroot ./debian/rules binary
mkdir -p dist
fakeroot ./debian/rules clean
rm debian/changelog
python setup.py clean
rmdir dist
mv -i ../*.deb .
echo "Made .deb"

